[package]
name = "multikeymap"
version = "0.1.0"
authors = ["Thomas Bytheway <tb403@cam.ac.uk>"]
edition = "2018"

[dependencies]
hashlike = { git = "https://github.com/DTG-FRESCO/hashlike-rs.git" }
maplit = "1.0"
